### ISSUE TITLE
Translate the learning contents into other languages

### ISSUE THREAD

**Issue by neila** [unchain-tech/UNCHAIN-projects#170]
## 提案内容
学習コンテンツを多言語対応させたい

`docs/[CONTENT_TITLE]/`下に `ja` の他にも `en` `es` `zh` など徐々に増やしていきたい

## 背景
良質なコンテンツが溜まりつつあるので言語によるアクセスへの障壁を取り除きたい

**Comment by neila** [comment]
DeepLに突っ込んでまともなアウトプットが出るかどうかは検証していないです
できそうなら適当なスクリプトを作って一括でガッとやりたい (DeepLのAPIリミットかかる気がするけど)

いずれにせよmarkdownなのでハイパーリンク等言語によって変えたりする必要がある可能性を考えると結局人力頼みの方がいいのだろうか？

**Comment by neila** [comment]
4月にETH Tokyoが来るので、それまでに学習コンテンツを英語だけでも用意できると、海外から集まって来る人たちもUNCHAINに巻き込むことができるのかなと思っています。翻訳できる方、大歓迎です！

**Comment by mashharuki** [comment]
#502 が新たに起案されたのでこちらはクローズ
