### ISSUE TITLE
ETH-dApp Section1 Lesson5 のサンプルコードのミス?

### ISSUE THREAD

**Issue by nc163** [unchain-tech/UNCHAIN-projects#325]
## 背景
discordで質問があったので調べて見たら変な気がして
ですが動作確認の方法も一から作るのは難しいので、確認したいです

## 備考

- https://app.unchain.tech/learn/ETH-dApp/ja/1/5/
- https://github.com/unchain-tech/UNCHAIN-projects/commit/10338d7225ca02794d143b4ea664ed2ef6138e83#r102414222

- discord
  - https://discord.com/channels/936573458748432405/946064452489469962/1080102407591178271

**Comment by neila** [comment]
ありがとうございます。 578625a74ee00132fd2a42448f3af7dbac8b7177 にて対応しました！
