### ISSUE TITLE
section1-5のコードにミスがある

### ISSUE THREAD

**Issue by takumi-mor** [unchain-tech/UNCHAIN-projects#327]
## 提案内容
deploy.js内の
`const waveContract = await waveContract.deploy();`は、
`const waveContract = await waveContractFactory.deploy();`ではないでしょうか？

## 背景
手順通り進めていたが、デプロイでReferenceError: Cannot access 'waveContract' before initializationが発生していた。

## 備考

https://app.unchain.tech/learn/ETH-dApp/ja/1/5/

**Comment by neila** [comment]
それであっています！ 🙇🏽

**Comment by neila** [comment]
https://github.com/unchain-tech/UNCHAIN-projects/commit/578625a74ee00132fd2a42448f3af7dbac8b7177
こちらにて修正を入れていますので、反映まで少々お待ちください！ 🙇🏽

**Comment by takumi-mor** [comment]
ありがとうございますー！
