### ISSUE TITLE
ETH dApp/section1/5 のコード修正報告

### ISSUE THREAD

**Issue by YungTatyu** [unchain-tech/UNCHAIN-projects#328]
## 提案内容
deploy.js　6行目を以下のように修正

【修正前】
const waveContract = await waveContract.deploy();

【修正後】
const waveContract = await waveContractFactory.deploy();

## 背景
コードのミスを発見したため報告します。

## 備考

https://app.unchain.tech/learn/ETH-dApp/ja/1/5/

**Comment by neila** [comment]
#327 duplicate
