### ISSUE TITLE
ETH-dApp_Added description of seed loading

### ISSUE THREAD

**Issue by nfttakerun** [unchain-tech/UNCHAIN-projects#430]
## 提案内容
dApp 開発プロジェクト Section4 Lesson1 のWavePortal.solにseedに関する追記
## 背景
上記講座ドキュメント掲載のコードでtestを実行するとseedの読み込みが行われないため、testが必ず失敗する
## 備考
WavePortal.solに下記コードを挿入することで解決しました。
function getSeed() private view returns (uint256) {
        return seed;
    }

https://app.unchain.tech/learn/ETH-dApp/ja/4/1/

**Comment by yk-saito** [comment]
@nfttakerun 
issue報告ありがとうございます！
こちらも #431 同様、 solidityのバージョンとエラー内容をご教授いただきたいです。

**Comment by nfttakerun** [comment]
solidityのバージョン：0.8.18
test実行後に表示されるエラーメッセージは以下の通りです。
Wave Contract
We have been constructed!
0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 has waved!
0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 won!
0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 has waved!
    1) test if wave and token are sent


  0 passing (2s)
  1 failing

  1) Wave Contract
       test if wave and token are sent:

      AssertionError: expected 0.0999 to equal 0.1
      + expected - actual

      -0.0999
      +0.1
      
      at Context.<anonymous> (test/test.js:59:49)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/takerun/.nvm/versions/node/v16.20.1/bin/node
Arguments: /Users/takerun/.npm-global/lib/node_modules/yarn/lib/cli.js test
Directory: /Users/takerun/Documents/unchain/ETH-dApp/packages/contract
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

UNCHAIN Disocrd内ACADEMY>ethereumチャンネルに2023年7月24日に同様の質問をさせていただきました。
