### ISSUE TITLE
ETH-dApp_Update description

### ISSUE THREAD

**Issue by nfttakerun** [unchain-tech/UNCHAIN-projects#431]
## 提案内容
dApp 開発プロジェクト Section4 Lesson1 のWavePortal.solの記述を一部修正
## 背景
上記講座ドキュメント掲載のコードにおいてVSCode上で.difficultyに警告が付きます。
## 備考
.difficulty→.prevrandaoに置き換えて解決しました。

https://app.unchain.tech/learn/ETH-dApp/ja/4/1/

**Comment by yk-saito** [comment]
@nfttakerun 
issue報告ありがとうございます！

開発で使用しているsolidityのバージョン（`hardhat.config.js`内）と、エラー内容をご教授いただきたいです。

**Comment by nfttakerun** [comment]
solidityのバージョン：0.8.18
VSCode上で表示される警告文は以下の通りです。
Since the VM version paris, "difficulty" was replaced by "prevrandao", which now returns a random number based on the beacon chain.solidity(8417)

**Comment by neila** [comment]
参考: 
- https://eips.ethereum.org/EIPS/eip-4399
- https://soliditydeveloper.com/prevrandao
