### ISSUE TITLE
ETH-NFT-Makerの内容を更新

### ISSUE THREAD

**Issue by neila** [unchain-tech/UNCHAIN-projects#449]
## 提案内容
見本コードと学習コンテンツで記載の内容に大きく乖離があるので、コンテンツの方に加筆修正を加える

## 備考
- ERC721URIStorageではなくERC721を継承
- https://github.com/unchain-tech/UNCHAIN-projects/blob/7afe26896a0421600ba9ac4d082560a506ffc1cf/docs/ETH-NFT-Maker/ja/section-1/lesson-4_NFT%E3%82%92%E7%99%BA%E8%A1%8C%E3%81%99%E3%82%8B%E3%82%B9%E3%83%9E%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%88%E3%83%A9%E3%82%AF%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86.md?plain=1#L55 setTokenURIではなく普通にTokenURIを用い、説明を端折らない

見本コントラクト https://github.com/unchain-tech/ETH-NFT-Maker/tree/complete/packages/contract/contracts

ドキュメント https://github.com/unchain-tech/UNCHAIN-projects/blob/main/docs/ETH-NFT-Maker/ja/section-1/lesson-4_NFT%E3%82%92%E7%99%BA%E8%A1%8C%E3%81%99%E3%82%8B%E3%82%B9%E3%83%9E%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%88%E3%83%A9%E3%82%AF%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86.md

**Comment by yk-saito** [comment]
[section1-lesson4](https://github.com/unchain-tech/UNCHAIN-projects/blob/main/docs/ETH-NFT-Maker/ja/section-1/lesson-4_NFT%E3%82%92%E7%99%BA%E8%A1%8C%E3%81%99%E3%82%8B%E3%82%B9%E3%83%9E%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%88%E3%83%A9%E3%82%AF%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86.md)では、おそらく下記の理由から`_setTokenURI`関数を使用してtokenURIを設定している

- ミントするトークンのメタデータは一種類のみ
- メタデータをjsonファイルとしてホストしたものを使用する（例:https://jsonkeeper.com/b/OLSM ）

[section2-lesson3](https://github.com/unchain-tech/UNCHAIN-projects/blob/main/docs/ETH-NFT-Maker/ja/section-2/lesson-3_ipfs%E3%82%92%E3%81%A4%E3%81%8B%E3%81%A3%E3%81%A6mint%E3%81%97%E3%82%88%E3%81%86%EF%BC%81.md)では、ミントするトークンを任意のものにするため、`tokenURI`関数を使用してコントラクト内でメタデータを構築している

（[定例](https://www.notion.so/unchain-shiftbase/dc4fd57fe8fe42e5a0e7d25a2285eef9?pvs=4#40f99799fdea4185815378b712d0c71b)より）

よって修正の必要はないとの結論になったので、こちらクローズします🙇
