### ISSUE TITLE
UNCHAINポータルサイトの再ホスティング

### ISSUE THREAD

**Issue by mashharuki** [unchain-tech/UNCHAIN-projects#486]
## 提案内容

1月31日を迎えると現行の形ではホスティングが停止するため、学習コンテンツをWebで見れるようにするために他の方法を検討する必要があります。

GitHub pagesとGitHub Actionsを利用してホスティングする形がお金もかからず簡単そうなのでそれが良さそうだと思ってます！
※ それかVercel。

学習コンテンツ自体はマークダウンファイルで作成されているためhonkitなどのツールが有効そう。

wevmが最近出した vocs等ツールも良さそう！！！

## 背景

1月31日を迎えると現行の形ではホスティングが停止するため。

## 備考

https://unchain.tech/

以下のツールが役立ちそう・・！！
https://github.com/honkit/honkit
https://github.com/wevm/vocs

https://zatta.link/web/docusaurus-how-to.html
↑ これも良さそう！！

その他の考慮事項として、パートナー企業のロゴやShiftbase社のロゴの削除
そしてログイン機能やメンバーのExplorer機能などは除外する必要あり

**Comment by neila** [comment]
markdownをhtmlで表示するツールは挙げていただいた honkit や wevm をはじめとしてや他にも[pandoc](https://pandoc.org/)や[remark](https://github.com/remarkjs/react-markdown)など割と無限にあるので、markdown描画ツールありきで考える必要性はあまりなく、新portal/viewerに求める構成とかホスティング上の制約とかUIだけ先に方向性決めてしまえば、あとはその制約に適したツールに適合する形でmarkdownを引っ張ってくることができるのかな、とか思っていました！参考までに

**Comment by mashharuki** [comment]
@neila ありがとうございます！！

**Comment by mashharuki** [comment]
① ホスティングサイトのUIの方向性
② ロゴ(今のものを使い続けるか新しく作るか)

などを先に決めた方が良さそう・・！！

**Comment by mashharuki** [comment]
<img width="2560" alt="スクリーンショット 2024-01-30 0 23 22" src="https://github.com/unchain-tech/UNCHAIN-projects/assets/44923695/2c89d325-f0f2-493b-adf8-3a4e4d113a29">
<img width="2560" alt="スクリーンショット 2024-01-30 0 23 11" src="https://github.com/unchain-tech/UNCHAIN-projects/assets/44923695/cf963d30-cd75-40b8-9949-67f9824a859a">
<img width="2560" alt="スクリーンショット 2024-01-30 0 23 00" src="https://github.com/unchain-tech/UNCHAIN-projects/assets/44923695/8de79b2e-5814-4d74-ab89-2dc5c46b81ab">
<img width="2560" alt="スクリーンショット 2024-01-30 0 22 48" src="https://github.com/unchain-tech/UNCHAIN-projects/assets/44923695/b0b9c43a-a957-4ef1-967e-56cfc909a1a8">

↑ 見れなくなる前に 2024年1月31日までのサイトのスクリーンショットを撮りました！！

**Comment by mashharuki** [comment]
https://www.awwwards.com/sites/yall-3
https://www.theonlineschool.com/
https://nextra.site/
https://nextra-docs-template.vercel.app/
https://github.com/shuding/nextra-docs-template/tree/main
https://docusaurus.io/ 

↑ 調べたやつ。結構色々ある・

**Comment by mashharuki** [comment]
https://unchain-tech.github.io/UNCHAIN-site/docs/intro
↑ docurousを使ってポータルサイトの候補を作ってみました。

**Comment by mashharuki** [comment]
https://github.com/unchain-tech/UNCHAIN-projects/tree/add_newportalsite
↑ブランチを切りました。

**Comment by nc163** [comment]
このリポジトリで管理するものはドキュメントのみとすることになったけど
docsaurus で利用されることは前提としてあるので、いくつか修正が必要です

- [ ] `<` `>` は制御文字として認識されてしまうので、使う場合は \` \` で括るようにする
- [ ] 画像のリンクミスがいくつかあるので修正する
- [ ] markdown内で <br> タグは使わないで、改行をする

あと何かあれば書き足します

**Comment by mashharuki** [comment]
再ホスティング自体は終わったのでクローズ
