### ISSUE TITLE
リンクのURL間違い

### ISSUE THREAD

**Issue by liverHawk** [unchain-tech/UNCHAIN-projects#503]
## 備考

上から3つ目のリンクで飛んだ際に404が出てしまう「ETH-dApp」

path: docs/AVAX-Messenger/ja/section-0/lesson-1_Avalancheネットワーク上でWEBアプリを構築しよう.md
https://github.com/unchain-tech/UNCHAIN-projects/blob/main/docs/AVAX-Messenger/ja/section-0/lesson-1_Avalanche%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E4%B8%8A%E3%81%A7WEB%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92%E6%A7%8B%E7%AF%89%E3%81%97%E3%82%88%E3%81%86.md

**Comment by Kyoya67** [comment]
https://github.com/unchain-tech/UNCHAIN-projects/pull/505

OSS活動初心者ですが、PR作ってみました。よろしくお願いします！
